### ISSUE TITLE
Error with Ranged Strike using Thrown Weapons

### ISSUE THREAD

**Issue by Mr-Monocyte** [yoshisman8/Wayfinder#15]
When I set up a melee Strike using a weapon with the Thrown trait, !strike works in Discord.

When I set up a ranged/throw Strike with the same weapon (e.g. Dagger), I get an error. After trying to figure it out, I found a workaround: Setting up the Strike as melee but using Dex for Attack and Str for Damage get the numbers correct but it still displays as a "melee" strike on the pf2.tools sheet.

Also, is there any functionality to automatically apply MAP to strikes? (i.e. to count the # of actions with the Attack trait. This should include Grapple/Shove/Trip Athletics checks)
Right now I'm having my players assign the penalty (e.g. !strike dagger -4) but they easily forget the penalty.

**Comment by yoshisman8** [comment]
I'll look into the first issue, you _should_ be able to just set the strike to ranged and it should work like that. I'll see why that isn't working.

As for MAP. There's unfortunately no plans on having MAP be auto calculated because of multiple reasons. For one, it's outside of the scope of the bot to be *that* automated. And for another there is just no easy way to program MAP into the bot without creating even more commands. So for now the only way to add MAP is to manually add the penalty to the roll itself. Sorry for the inconvenience

**Comment by yoshisman8** [comment]
The issue has been addressed in commit [c06aa92](https://github.com/yoshisman8/Wayfinder/commit/c06aa928eba2bc2ceeedefcfba5aa138c036fb76)

**Comment by Mr-Monocyte** [comment]
Understandable. I was just hoping that MAP could be built into the encounter script(s) to count the number of !strike commands (Grapple/Shove/Trip "Strikes" could be created) Then when !strike is called it could read the count, apply the penalty (-5*count, -4*count for Agile, ?*count for Ranger/DW; this info is already included in the pf2.tools attack), and add 1 to the count. The count would be reset to 0 at the start of each of their turns.

I wish I could help implement this, but I'm only experienced with Python.

Thanks for your quick response and for all the work you've put in. Wayfinder is amazing.

One last thing: for !Save, the functional arguments I've found are: "fort", "fortitude", "reflex" & "will". Is it possible to add "f", "r" and "w" as accepted abbreviations for those saves?

**Comment by yoshisman8** [comment]
I can, in fact implement said shortcuts. Good suggestion! I'll implement those shorthands right now. 

Maybe at some later I can look into implementing MAP. The problem with it is that the initiative tracker doesn't really track actions. There's also the problem that some actions count as 2 actions for MAP (like power attack or double slice) so I opted to not automate those so players can more fine tune what penalties they have

**Comment by Mr-Monocyte** [comment]
Yeah, the attack count would have to be tracked outside the initiative tracker, huh? At least the number of actions are already included in each pf2.tools attack object.

Thanks again for all your work!

**Comment by Mr-Monocyte** [comment]
**Ranged** Strikes with Thrown Weapons now work in Discord but the Strength modifier bonus to damage is __not__ being applied. Normal ranged weapons don't get a bonus to damage but Thrown weapons get strength_mod added to damage.

**Comment by Mr-Monocyte** [comment]
Also the default unarmed "fist" attack (default added when clicking the (+) on the pf2.tools attack card doesn't work when calling the strike in Discord. Specifying it as a "Weapon" or "Melee" attack via the inspector avoids the error message and gets a roll but the damage shown is "untyped" instead of bludgeoning.

**Comment by yoshisman8** [comment]
Does it not add STR to damage even if you set it manually? If so this is a problem with character.pf2.tools rather than my bot sadly. Also, unarmed attacks are a headache to work with. My suggestion is to make unarmed strikes custom strikes

**Comment by Mr-Monocyte** [comment]
Ah, yes, it does look like an issue with character.pf2.tools. A "Ranged" Strike won't add bonus damage even if it's set manually for Strength. Sorry for the confusion.

So it looks like custom is the way to go for thrown weapons as well?

**Comment by yoshisman8** [comment]
For now it seems so, i'll tell Kyle to let the user set modifier damage on ranged attacks too
