### ISSUE TITLE
Fix Dice Roller typo multiplication with parentheses.

### ISSUE THREAD

**Issue by Laiot** [yoshisman8/Wayfinder#3]
I noticed that when you try to multiplicate the argument of a dice rolling, there is a weird typo printing the result. Basically it prints the closing parentheses twice. EG:
`!roll (2d6+2)*2`
returns:
`User rolled some dice.`
`) :d6_3: + :d6_5: + 2 ) * 2`
`Total = 20`

I tried to fix it in Dice Modules.cs (also don't use whitespaces in files name) but I couldn't find where you print the result before 'Total'. I think the problem is line 41 but I'm not sure.

**Comment by yoshisman8** [comment]
Fixed in [this commit ](https://github.com/yoshisman8/Wayfinder/commit/53865cb0052dda7e1386ac76229b9bc070944a94)
