### ISSUE TITLE
Actions aren't displayed correctly

### ISSUE THREAD

**Issue by qnicoud** [yoshisman8/Wayfinder#6]
When asking for the list of actions, it  displays the list of feats instead, and then it won't find any of the description of the actions when asked to.

On discord trying the commands:
 ![wayfinder_action_issue](https://user-images.githubusercontent.com/47816676/80312756-51ee7a80-87e7-11ea-8d0b-1893954991c2.png)

On my character.pf2.tools page, feat section:
![wayfinder_action_issue_feats](https://user-images.githubusercontent.com/47816676/80312824-cd502c00-87e7-11ea-975a-9176425b0fde.png)

On my character.pf2.tools page, action section:
![wayfinder_action_issue_actionspng](https://user-images.githubusercontent.com/47816676/80312812-c32e2d80-87e7-11ea-94eb-d65cdb9cce26.PNG)

**Comment by yoshisman8** [comment]
hmm it seems like the !actions command isn't reading from the actions you get from feats. I'll get onto this as soon as i can! Thanks for reporting it!

**Comment by yoshisman8** [comment]
Can you provide me with the link to your character sheet. I can't seem to be able replicate the bug with my own characters. @qnicoud

**Comment by qnicoud** [comment]
oh, so maybe it isn't set up correctly. Maybe worth to mention, I did not generated the actions manually as character.pf2.tools does it automatically from the feats.
Here is the character sheet :
https://character.pf2.tools/?4W7R6ywy-muraizur

**Comment by yoshisman8** [comment]
Thanks! I found the issue already. It seemes like i forgot to make function that searches through Actions and Feats only return null if _both_ feats and Actions are null. It was set up so that, if you had no actions in the Actions tab, it will always return null even if you had actions derived from the Feats tab. A fix will be comitted shortly! Thanks for the bug report!

**Comment by yoshisman8** [comment]
Issue fixed in Commit [ac077fb](https://github.com/yoshisman8/Wayfinder/commit/ac077fbf0671205c109216246708c199a5bb8f04)
